name: manga
description: Remote manga website through app and Chrome Extension.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.2.0

  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
